name: shopkeeper_app
description: Offline Sewa — shopkeeper mobile app.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^5.2.3
  file_picker: ^8.1.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  sewa_core:
    path: ../packages/sewa_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
